version: "3.8"

services:
  # Home Server Proxy for any *.sor4chi.com
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - home-network

  # Monitoring service
  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - home-network

networks:
  home-network:
    driver: bridge

volumes:
  grafana-storage:
